# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=500)),
                ('document_title', models.CharField(max_length=500)),
                ('security_level', models.CharField(max_length=500)),
                ('investigation_number', models.CharField(max_length=500)),
                ('investigation_phase', models.CharField(max_length=500)),
                ('investigation_status', models.CharField(max_length=500)),
                ('investigation_title', models.CharField(max_length=500)),
                ('investigation_type', models.CharField(max_length=500)),
                ('firm_organization', models.CharField(max_length=500)),
                ('filedby', models.CharField(max_length=500)),
                ('onbehalfof', models.CharField(max_length=500)),
                ('documentdate', models.DateTimeField(verbose_name='Document Date')),
                ('officialrecieveddate', models.DateTimeField(verbose_name='Received Date')),
                ('document_link', models.CharField(max_length=500)),
                ('modified_date', models.DateTimeField(verbose_name='Modified Date')),
            ],
        ),
    ]
