# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=500)),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.Account')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.Notification')),
            ],
        ),
    ]
