# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, verbose_name='Due Date'),
        ),
    ]
